version: '3.8'
services:
  api:
    image: mnemos-api:latest
    container_name: mnemos-api
    restart: unless-stopped
    env_file:
      - /etc/mnemos/api.env
    ports:
      - '127.0.0.1:4000:4000'
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: mnemos-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: mnemos
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: mnemos_prod
    volumes:
      - /var/lib/mnemos-db:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5432:5432'
