/* eslint-disable */
/* tslint:disable */
// This file was automatically generated by orval
import { api } from './client';

export type HealthResponse = {
  ok: true;
  ts: string;
};

export type RecordItem = {
  id: string;
  title: string;
  content: string | null;
  createdAt: string;
  updatedAt: string;
};

export type RecordCreate = {
  title: string;
  content?: string;
};

export type RecordUpdate = {
  title?: string;
  content?: string | null;
};

export type OperationResult = {
  ok: true;
};

export const getApiHealth = (options?: RequestInit) =>
  api<HealthResponse>('/api/health', { ...(options ?? {}), method: 'GET' });

export const getApiRecords = (options?: RequestInit) =>
  api<RecordItem[]>('/api/records', { ...(options ?? {}), method: 'GET' });

export const postApiRecords = (data: RecordCreate, options?: RequestInit) =>
  api<RecordItem>('/api/records', {
    body: JSON.stringify(data),
    ...(options ?? {}),
    method: 'POST',
  });

export const putApiRecordsId = (id: string, data: RecordUpdate, options?: RequestInit) =>
  api<RecordItem>(`/api/records/${id}`, {
    body: JSON.stringify(data),
    ...(options ?? {}),
    method: 'PUT',
  });

export const deleteApiRecordsId = (id: string, options?: RequestInit) =>
  api<OperationResult>(`/api/records/${id}`, { ...(options ?? {}), method: 'DELETE' });
