import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

import { buildServer } from '../server';

const OPENAPI_JSON_RELATIVE_PATH = '../../../packages/types/openapi.json';
const OPENAPI_TYPES_RELATIVE_PATH = '../../../packages/types/src/openapi.ts';

async function main() {
  const server = await buildServer();
  await server.ready();

  const document = server.swagger();

  const specPath = resolve(__dirname, OPENAPI_JSON_RELATIVE_PATH);
  await mkdir(dirname(specPath), { recursive: true });
  await writeFile(specPath, JSON.stringify(document, null, 2));

  const typesPath = resolve(__dirname, OPENAPI_TYPES_RELATIVE_PATH);
  await mkdir(dirname(typesPath), { recursive: true });
  const serializedDocument = JSON.stringify(document, null, 2);
  const source = `/**\n * This file is auto-generated by the API service. Do not edit manually.\n */\nexport const openapi = ${serializedDocument} as const;\n\nexport type OpenAPIDocument = typeof openapi;\nexport type Paths = OpenAPIDocument['paths'];\nexport type Components = NonNullable<OpenAPIDocument['components']>;\n`;
  await writeFile(typesPath, source);

  await server.close();
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
