name: Deploy (Ubuntu)

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]

    env:
      TARGET_WEB: /var/www/mnemos
      TARGET_API: /srv/mnemos-api
      API_SERVICE: mnemos-api

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.19.0"

      - name: Enable pnpm via corepack
        run: |
          corepack enable
          corepack prepare pnpm@10 --activate
          pnpm -v

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      # --- FRONTEND ---
      - name: Ensure web dir (owned by runner)
        run: mkdir -p "$TARGET_WEB"

      - name: Upload web to nginx root
        run: rsync -a --delete apps/web/dist/ "$TARGET_WEB"/

      # --- BACKEND ---
      - name: Prepare API dir
        run: |
          mkdir -p "$TARGET_API"
          # удалить содержимое, но не сам каталог
          find "$TARGET_API" -mindepth 1 -maxdepth 1 -exec rm -rf {} +

      - name: Deploy API package
        run: pnpm deploy --filter "@mnemos/api" --prod --legacy "$TARGET_API"

      - name: Copy .env (optional)
        run: |
          if [ -f apps/api/.env ]; then cp -f apps/api/.env "$TARGET_API"/; fi

      - name: Reload API with PM2
        run: |
          corepack prepare pnpm@10 --activate
          APP="$TARGET_API/dist/main.js"
          [ -f "$APP" ] || (echo "entry not found: $APP" && exit 1)
          npx pm2 describe "$API_SERVICE" >/dev/null 2>&1 || \
            npx pm2 start "$APP" --name "$API_SERVICE" --cwd "$TARGET_API" --update-env --time
          npx pm2 reload "$API_SERVICE"
          npx pm2 save
