name: Deploy to Ubuntu host

on:
  push:
    branches: ["master"]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: [self-hosted, Ubuntu, X64]
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.19.0
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.0
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build web client
        run: pnpm --filter @mnemos/web build

      - name: Publish web client to nginx root
        run: |
          sudo install -d -m 0755 /var/www/mnemos
          sudo rsync -a --delete apps/web/dist/ /var/www/mnemos/

      - name: Build API service
        run: pnpm --filter @mnemos/api build

      - name: Package API for production
        run: |
          rm -rf /tmp/mnemos-api
          pnpm deploy --filter @mnemos/api --prod /tmp/mnemos-api

      - name: Publish API bundle
        run: |
          sudo install -d -m 0755 /opt/mnemos/api
          sudo rsync -a --delete /tmp/mnemos-api/ /opt/mnemos/api/

      - name: Restart API service
        run: sudo systemctl reload-or-restart mnemos-api.service
