name: Build & Deploy (Windows Server)

on:
  push:
    branches: [ "master" ]  # автодеплой при пуше в master

jobs:
  build-deploy:
    runs-on: [self-hosted, Windows]
    env:
      TARGET_WEB: C:\www\mnemos
      TARGET_API: C:\srv\mnemos-api
      API_SERVICE: mnemos-api
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.19.0"

      - name: Install PNPM
        run: npm i -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build all apps
        run: pnpm build

      # --- FRONTEND ---
      - name: Deploy frontend to nginx www
        shell: cmd
        run: |
          if not exist "%TARGET_WEB%" mkdir "%TARGET_WEB%"
          robocopy apps\web\dist "%TARGET_WEB%" /MIR
          if %ERRORLEVEL% LEQ 7 exit /B 0
          exit /B %ERRORLEVEL%

      # --- BACKEND ---

      # 0) Поставить прод-зависимости для API в рабочей копии
      - name: Prepare API production deps
        working-directory: apps/api
        run: pnpm install --prod
  
      # 2) Деплой бэкенда (как уже сделали)
      - name: Deploy backend build
        shell: cmd
        run: |
          @echo off
          if not exist "%TARGET_API%" mkdir "%TARGET_API%"
          robocopy apps\api\dist "%TARGET_API%\dist" /MIR
          if %ERRORLEVEL% GTR 7 exit /B %ERRORLEVEL%
          robocopy apps\api\node_modules "%TARGET_API%\node_modules" /MIR
          if %ERRORLEVEL% GTR 7 exit /B %ERRORLEVEL%
          copy /Y apps\api\package.json "%TARGET_API%\"
          if exist apps\api\pnpm-lock.yaml copy /Y apps\api\pnpm-lock.yaml "%TARGET_API%\"
          if exist apps\api\.env copy /Y apps\api\.env "%TARGET_API%\"

      # 3) (минимальный фикс 1069) Запускать от LocalSystem
      - name: Set service to LocalSystem (avoid 1069)
        shell: cmd
        run: |
          @echo off
          sc config "%API_SERVICE%" obj= "LocalSystem"
          rem останавливать тихо (если не запущена — ок)
          sc stop "%API_SERVICE%" >nul 2>&1
          rem старт
          sc start "%API_SERVICE%"
          rem показать состояние для журнала
          sc query "%API_SERVICE%"
