name: Deploy (Docker + Nginx with wrapper)

on:
  push:
    branches: ["master"]

permissions:
  contents: read

concurrency:
  group: mnemos-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]
    timeout-minutes: 30

    env:
      WEB_ROOT: /var/www/mnemos
      DEPLOY_DIR: /home/runner/deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.19.0
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # --- WEB ---
      - name: Build web
        run: pnpm --filter ./apps/web build

      - name: Publish web to Nginx root (no sudo needed because runner owns the dir)
        run: |
          mkdir -p "${RUNNER_TEMP}/mnemos-web"
          rsync -a --delete apps/web/dist/ "${RUNNER_TEMP}/mnemos-web/"
          rsync -a --delete "${RUNNER_TEMP}/mnemos-web/" "$WEB_ROOT/"
          # проверим nginx конфиг и перезагрузим через wrapper (sudo)
          sudo /usr/local/bin/mnemos-reload-nginx.sh

      # --- API (Docker) ---
      - name: Copy compose to deploy dir (so server has it)
        run: |
          mkdir -p "$DEPLOY_DIR"
          cp -r deploy/* "$DEPLOY_DIR/"

      - name: Build API Docker image
        working-directory: apps/api
        run: docker build -t mnemos-api:latest .

      - name: Run docker-compose deploy via wrapper
        run: sudo /usr/local/bin/mnemos-docker-deploy.sh

      - name: Health check (best-effort)
        continue-on-error: true
        run: curl -fsS http://127.0.0.1:4000/api/health || true
