name: Deploy (Docker + Nginx with wrapper)

on:
  push:
    branches: ["master"]

permissions:
  contents: read

concurrency:
  group: mnemos-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]
    timeout-minutes: 30

    env:
      WEB_ROOT: /var/www/mnemos
      DEPLOY_DIR: /home/runner/deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.19.0
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      # --- WEB: ставим ТОЛЬКО то, что нужно для web и его зависимостей
      - name: Install deps for web only
        run: pnpm install --frozen-lockfile --filter ./apps/web...

      # --- WEB ---
      - name: Build web
        run: pnpm --filter ./apps/web build

      - name: Publish web to Nginx root
        run: |
          mkdir -p "${RUNNER_TEMP}/mnemos-web"
          rsync -a --delete apps/web/dist/ "${RUNNER_TEMP}/mnemos-web/"
          rsync -a --delete "${RUNNER_TEMP}/mnemos-web/" "$WEB_ROOT/"
          # проверим nginx конфиг и перезагрузим через wrapper (sudo)
          sudo /usr/local/bin/mnemos-reload-nginx.sh

      # --- API (Docker): compose и образ живут своей жизнью
      - name: Sync compose to deploy dir
        run: |
          mkdir -p "$DEPLOY_DIR"
          cp -r deploy/* "$DEPLOY_DIR/"

      # --- DB (первый раз или при обновлении версии Postgres/окружения)
      # если БД уже крутится стабильно, этот шаг можно пропускать
      - name: Ensure DB is up
        run: sudo /usr/local/bin/mnemos-docker-db-deploy.sh

      - name: Build API Docker image
        run: docker build -t mnemos-api:latest -f apps/api/Dockerfile .

      - name: Run docker-compose deploy via wrapper
        run: sudo /usr/local/bin/mnemos-docker-deploy.sh

      # --- Prisma migrations (обновляют схему без перезапуска контейнеров)
      - name: Run Prisma migrations
        run: sudo /usr/local/bin/mnemos-api-migrate.sh

      # --- Health checks (best-effort)
      - name: Health check API
        continue-on-error: true
        run: curl -fsS http://127.0.0.1:4000/api/health || true

      - name: Health check DB
        continue-on-error: true
        run: docker exec mnemos-db pg_isready -U mnemos -d mnemos_prod || true
