name: Build & Deploy (Windows Server)

on:
  push:
    branches: [ "master" ]  # автодеплой при пуше в master

jobs:
  build-deploy:
    runs-on: [self-hosted, Windows]
    env:
      TARGET_WEB: C:\www\mnemos
      TARGET_API: C:\srv\mnemos-api
      API_SERVICE: mnemos-api
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.19.0"

      - name: Install PNPM
        run: npm i -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build all apps
        run: pnpm build

      # --- FRONTEND ---
      - name: Deploy frontend to nginx www
        shell: cmd
        run: |
          if not exist "%TARGET_WEB%" mkdir "%TARGET_WEB%"
          robocopy apps\web\dist "%TARGET_WEB%" /MIR
          if %ERRORLEVEL% LEQ 7 exit /B 0
          exit /B %ERRORLEVEL%

      # --- BACKEND ---
  
      # 1) Копируем сборку и node_modules + манифест
      - name: Deploy backend build
        shell: cmd
        run: |
          @echo off
          if not exist "%TARGET_API%" mkdir "%TARGET_API%"
          rem dist
          robocopy apps\api\dist "%TARGET_API%\dist" /MIR
          if %ERRORLEVEL% GTR 7 exit /B %ERRORLEVEL%
          rem node_modules (продовые, уже установлены шагом выше)
          robocopy apps\api\node_modules "%TARGET_API%\node_modules" /MIR
          if %ERRORLEVEL% GTR 7 exit /B %ERRORLEVEL%
          rem package.json (lock в цель НЕ копируем — он не нужен)
          copy /Y apps\api\package.json "%TARGET_API%\"
          if exist apps\api\.env copy /Y apps\api\.env "%TARGET_API%\"

      # 2) Перезапуск через PM2
      - name: Reload API with PM2
        shell: cmd
        run: |
          @echo off
          where pm2 >nul 2>&1 || (echo [ERROR] pm2 not found. Run 'npm i -g pm2' on the server & exit /b 1)
          pm2 describe mnemos-api >nul 2>&1 || pm2 start "%TARGET_API%\dist\main.js" --name mnemos-api --cwd "%TARGET_API%" --update-env --time
          pm2 reload mnemos-api
          pm2 save
