name: Deploy (Ubuntu)

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]

    env:
      TARGET_WEB: /var/www/mnemos
      TARGET_API: /srv/mnemos-api
      API_SERVICE: mnemos-api

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.19.0"

      - name: Enable pnpm via corepack
        run: |
          corepack enable
          corepack prepare pnpm@10 --activate
          pnpm -v

      - name: Install deps
        run: pnpm install --no-frozen-lockfile

      - name: Build
        run: pnpm build

      # --- FRONTEND ---
      - name: Ensure web dir (owned by runner)
        run: mkdir -p "$TARGET_WEB"

      - name: Upload web to nginx root
        run: rsync -a --delete apps/web/dist/ "$TARGET_WEB"/

      # --- BACKEND ---
      - name: Stop API before deploy (if running)
        run: npx pm2 stop mnemos-api || true

      - name: Prepare target dir (keep folder, clean contents)
        run: |
          mkdir -p /srv/mnemos-api
          find /srv/mnemos-api -mindepth 1 -maxdepth 1 -exec rm -rf {} +

      - name: Build deploy bundle in a temp dir (resolves workspaces)
        env:
          DEPLOY_TMP: ${{ runner.temp }}/api-deploy
        run: |
          rm -rf "$DEPLOY_TMP"
          mkdir -p "$DEPLOY_TMP"
          # pnpm сам соберёт прод-набор зависимостей для api БЕЗ workspace:* сбоев
          pnpm deploy --filter "@mnemos/api" --prod --legacy "$DEPLOY_TMP"

      - name: Sync deploy bundle to target
        env:
          DEPLOY_TMP: ${{ runner.temp }}/api-deploy
        run: |
          rsync -a --delete "$DEPLOY_TMP"/ /srv/mnemos-api/
          # если есть .env в репо — скопируем поверх (не обязательно)
          if [ -f apps/api/.env ]; then
            rsync -a apps/api/.env /srv/mnemos-api/.env
          fi

      - name: Start/Reload API with PM2
        run: |
          APP="/srv/mnemos-api/dist/main.js"
          [ -f "$APP" ] || (echo "entry not found: $APP" && exit 1)
          npx pm2 describe mnemos-api >/dev/null 2>&1 || \
            npx pm2 start "$APP" --name mnemos-api --cwd /srv/mnemos-api --update-env --time
          npx pm2 reload mnemos-api || npx pm2 start "$APP" --name mnemos-api --cwd /srv/mnemos-api --update-env --time
          npx pm2 save


