name: Build & Deploy (Windows Server)

on:
  push:
    branches: [ "master" ]  # автодеплой при пуше в master

jobs:
  build-deploy:
    runs-on: [self-hosted, Windows]
    env:
      TARGET_WEB: C:\www\mnemos
      TARGET_API: C:\srv\mnemos-api
      API_SERVICE: mnemos-api
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.19.0"

      - name: Install PNPM
        run: npm i -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build all apps
        run: pnpm build

      # --- FRONTEND ---
      - name: Deploy frontend to nginx www
        shell: cmd
        run: |
          if not exist "%TARGET_WEB%" mkdir "%TARGET_WEB%"
          robocopy apps\web\dist "%TARGET_WEB%" /MIR
          if %ERRORLEVEL% LEQ 7 exit /B 0
          exit /B %ERRORLEVEL%

      - name: Restart API service (best-effort)
        shell: cmd
        run: |
          @echo off
          rem если службы нет — выходим молча
          sc query "%API_SERVICE%" >nul 2>&1 || exit /b 0
          rem пытаемся остановить, ошибки игнорируем (в т.ч. 1062)
          sc stop "%API_SERVICE%" >nul 2>&1
          rem пробуем запустить
          sc start "%API_SERVICE%" >nul 2>&1 || sc query "%API_SERVICE%"

      - name: Deploy backend build
        shell: cmd
        run: |
          if not exist "%TARGET_API%" mkdir "%TARGET_API%"
          robocopy apps\api\dist "%TARGET_API%\dist" /MIR
          if %ERRORLEVEL% LEQ 7 exit /B 0
          exit /B %ERRORLEVEL%

      - name: Install production dependencies for API
        working-directory: C:\srv\mnemos-api
        run: pnpm install --prod

      - name: Restart API service
        shell: cmd
        run: sc start %API_SERVICE%
